{
  home.file.".local/share/PrismLauncher/prismlauncher.cfg".text = ''
    [General]
    ApplicationTheme=system
    AutoCloseConsole=false
    BackgroundCat=teawie
    CentralModsDir=mods
    CloseAfterLaunch=false
    ConfigVersion=1.2
    ConsoleFont=IPAGothic
    ConsoleFontSize=11
    ConsoleMaxLines=100000
    ConsoleOverflowStop=true
    ConsoleWindowGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAABM0AAAP0AAAAAAAAAAAAAAd/AAAEDAAAAAACAAAAB4AAAAAAAAAAAAAABM0AAAP0)
    ConsoleWindowState=@ByteArray(AAAA/wAAAAD9AAAAAAAABM4AAAP1AAAABAAAAAQAAAAIAAAACPwAAAAA)
    CustomGLFWPath=
    CustomOpenALPath=
    DownloadsDir=/home/hezaki/Downloads
    DownloadsDirWatchRecursive=false
    EnableFeralGamemode=true
    EnableMangoHud=false
    Env=@Variant(\0\0\0\b\0\0\0\0)
    FlameKeyOverride=
    IconTheme=flat_white
    IconsDir=icons
    IgnoreJavaCompatibility=false
    IgnoreJavaWizard=false
    InstSortMode=Name
    InstanceDir=instances
    JProfilerPath=
    JVisualVMPath=
    JavaArchitecture=64
    JavaPath=/nix/store/2vwkssqpzykk37r996cafq7x63imf4sp-openjdk-21+35/bin/java
    JavaRealArchitecture=amd64
    JavaSignature=590809d184bb3d91474cdc877fc0b4fa19807f52
    JavaVendor=N/A
    JavaVersion=21
    JsonEditor=
    JvmArgs=
    Language=en_US
    LastHostname=think
    LastUsedGroupForNewInstance=
    LaunchMaximized=true
    MCEditPath=
    MSAClientIDOverride=
    MainWindowGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAABM0AAAP0AAAAAAAAAAD////+/////gAAAAACAAAAB4AAAAAAAAAAAAAABM0AAAP0)
    MainWindowState="@ByteArray(AAAA/wAAAAD9AAAAAAAAB2gAAAOeAAAABAAAAAQAAAAIAAAACPwAAAADAAAAAQAAAAEAAAAeAGkAbgBzAHQAYQBuAGMAZQBUAG8AbwBsAEIAYQByAgAAAAD/////AAAAAAAAAAAAAAACAAAAAQAAABYAbQBhAGkAbgBUAG8AbwBsAEIAYQByAAAAAAD/////AAAAAAAAAAAAAAADAAAAAQAAABYAbgBlAHcAcwBUAG8AbwBsAEIAYQByAAAAAAD/////AAAAAAAAAAA=)"
    MaxMemAlloc=8096
    MenuBarInsteadOfToolBar=true
    MetaURLOverride=
    MinMemAlloc=512
    MinecraftWinHeight=480
    MinecraftWinWidth=854
    ModDependenciesDisabled=false
    ModDownloadGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAABI0AAAI4AAAAAAAAAAAAAAMqAAABsQAAAAACAAAAB4AAAAAAAAAAAAAABI0AAAI4)
    ModMetadataDisabled=false
    ModrinthToken=
    NewInstanceGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAAB30AAAQMAAAAAAAAAAAAAAd9AAAEDAAAAAACAAAAB4AAAAAAAAAAAAAAB30AAAQM)
    NumberOfConcurrentDownloads=6
    NumberOfConcurrentTasks=10
    OnlineFixes=false
    PagedGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAABSYAAALPAAAAAAAAAAAAAAUmAAACzwAAAAACAAAAB4AAAAAAAAAAAAAABSYAAALP)
    PastebinCustomAPIBase=
    PastebinType=3
    PermGen=128
    PostExitCommand=
    PreLaunchCommand=
    ProxyAddr=127.0.0.1
    ProxyPass=
    ProxyPort=8080
    ProxyType=None
    ProxyUser=
    QuitAfterGameStop=false
    RPDownloadGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAAB38AAAQ3AAAAAAAAAAAAAANOAAABrQAAAAACBAAAB4AAAAAAAAAAAAAAB38AAAQ3)
    RecordGameTime=true
    SelectedInstance=1.21-pre2
    ShaderDownloadGeometry=@ByteArray(AdnQywADAAAAAAAAAAAAAAAAA0YAAAGxAAAAAAAAAAD////+/////gAAAAACAAAAB4AAAAAAAAAAAAAAA0YAAAGx)
    ShowConsole=false
    ShowConsoleOnError=true
    ShowGameTime=true
    ShowGameTimeWithoutDays=true
    ShowGlobalGameTime=true
    TheCat=false
    ToolbarsLocked=false
    UseDiscreteGpu=false
    UseNativeGLFW=false
    UseNativeOpenAL=false
    UseSystemLocale=true
    UserAgentOverride=
    WideBarVisibility_coremods="@ByteArray(1111111111,JWdCHzvbkGygavwHUmucz5o2JI0=)"
    WideBarVisibility_instanceToolBar="@ByteArray(111111111,BpBQWIumr+0ABXFEarV0R5nU0iY=)"
    WideBarVisibility_mods="@ByteArray(111111111,YVzEf6yx8HK0+6mXAzcAlYWNI7g=)"
    WideBarVisibility_resourcepacks="@ByteArray(1111111,lW4z/kgDfZm/2iUpafuxPiRwFuA=)"
    WideBarVisibility_screenshots="@ByteArray(111111,1E/BPQ4NUAzOwtfKiXviX1IZMyM=)"
    WideBarVisibility_servers="@ByteArray(11111,MNzO4OpOJqHt8mTb5JBHEUSjWos=)"
    WideBarVisibility_shaderpacks="@ByteArray(1111111,7Za9P041Ly89fzbDFRBdPwQCnAA=)"
    WideBarVisibility_version="@ByteArray(11111111111111111,tXhw3ycXgSIjnk/9vC7okj8Uqdk=)"
    WideBarVisibility_worlds="@ByteArray(1111111111,N3MvzT17SHBCSvhDW7SQ/e7aDIc=)"
    WrapperCommand=
  '';
}
