{ config, ... }:
with config.lib.stylix.colors.withHashtag;
{
  home = {
    file."Documents/Notes/.obs.desktop/plugins/obsidian-style-settings/data.json".text = # json
      ''
        {
          "anuppuccin-theme-settings@@ctp-custom-red@@dark": "#e62d42",
          "anuppuccin-theme-settings@@ctp-custom-yellow@@dark": "#c88800",
          "anuppuccin-theme-settings@@ctp-custom-green@@dark": "#3a944a",
          "anuppuccin-theme-settings@@ctp-custom-crust@@dark": "#222226",
          "anuppuccin-theme-settings@@ctp-custom-base@@dark": "#28282c",
          "anuppuccin-theme-settings@@ctp-custom-mantle@@dark": "#28282c",
          "anuppuccin-theme-settings@@ctp-custom-surface0@@dark": "#36363a",
          "anuppuccin-theme-settings@@ctp-custom-surface1@@dark": "#36363a",
          "anuppuccin-theme-settings@@ctp-custom-surface2@@dark": "#36363a",
          "anuppuccin-theme-settings@@ctp-custom-overlay0@@dark": "#36363a",
          "anuppuccin-theme-settings@@ctp-custom-overlay1@@dark": "#36363a",
          "anuppuccin-theme-settings@@ctp-custom-subtext0@@dark": "#6f8396",
          "anuppuccin-theme-settings@@ctp-custom-overlay2@@dark": "#ffffff",
          "anuppuccin-theme-settings@@ctp-custom-subtext1@@dark": "#ffffff",
          "anuppuccin-theme-settings@@ctp-custom-text@@dark": "#ffffff",
          "anuppuccin-theme-settings@@ctp-custom-lavender@@dark": "#3584e4",
          "anuppuccin-theme-settings@@ctp-custom-blue@@dark": "#3584e4",
          "anuppuccin-theme-settings@@ctp-custom-sapphire@@dark": "#3584e4",
          "anuppuccin-theme-settings@@ctp-custom-sky@@dark": "#3584e4",
          "anuppuccin-theme-settings@@ctp-custom-teal@@dark": "#2190a4",
          "anuppuccin-theme-settings@@ctp-custom-peach@@dark": "#ed5b00",
          "anuppuccin-theme-settings@@ctp-custom-maroon@@dark": "#e62d42",
          "anuppuccin-theme-settings@@ctp-custom-mauve@@dark": "#9141ac",
          "anuppuccin-theme-settings@@ctp-custom-pink@@dark": "#d56199",
          "anuppuccin-theme-settings@@ctp-custom-rosewater@@dark": "#3584e4",
          "anuppuccin-theme-settings@@ctp-custom-flamingo@@dark": "#ffffff",

          "anuppuccin-theme-settings@@anp-canvas-dark-bg": false,
          "anuppuccin-theme-settings@@anp-custom-vault-toggle": false,
          "anuppuccin-theme-settings@@anp-file-icons": true,
          "anuppuccin-theme-settings@@anp-alt-rainbow-style": "anp-default-rainbow",
          "anuppuccin-theme-settings@@anp-collapse-folders": true,
          "anuppuccin-theme-settings@@anp-floating-header": false,
          "anuppuccin-theme-settings@@anp-alt-tab-style": "anp-safari-tab-toggle",
          "anuppuccin-theme-settings@@anp-disable-newtab-align": true,
          "anuppuccin-theme-settings@@anp-hide-external-link-icon": false,
          "anuppuccin-theme-settings@@anp-tooltip-toggle": false,
          "anuppuccin-theme-settings@@anp-toggle-scrollbars": false,
          "anuppuccin-theme-settings@@anp-hide-status-bar": false,
          "anuppuccin-theme-settings@@anp-autohide-titlebar": false,
          "anuppuccin-theme-settings@@anp-active-line": "anp-current-line-border",
          "anuppuccin-theme-settings@@anp-custom-checkboxes": true,
          "anuppuccin-theme-settings@@anp-colorful-frame": false,
          "anuppuccin-theme-settings@@anp-colorful-frame-icon-toggle-light": false,
          "anuppuccin-theme-settings@@anp-colorful-frame-icon-toggle-dark": false,
          "anuppuccin-theme-settings@@anp-layout-select": "anp-card-layout",
          "anuppuccin-theme-settings@@anp-bg-fix": false,
          "anuppuccin-theme-settings@@anp-hide-borders": false,
          "anuppuccin-theme-settings@@anp-card-layout-actions": false,
          "anuppuccin-theme-settings@@anp-card-layout-filebrowser": true,
          "anuppuccin-theme-settings@@anp-card-shadows": false,
          "anuppuccin-theme-settings@@anp-safari-tab-animated": false,
          "anuppuccin-theme-settings@@anp-alt-tab-custom-height": 40,
          "anuppuccin-theme-settings@@anp-status-bar-select": "none",
          "anuppuccin-theme-settings@@anp-toggle-preview": false,
          "anuppuccin-theme-settings@@anp-table-toggle": false,
          "anuppuccin-theme-settings@@anp-table-auto": false,
          "anuppuccin-theme-settings@@anp-speech-bubble": true,
          "anuppuccin-theme-settings@@anp-safari-tab-radius": 16
        }
      '';
  };
}
