#!/bin/env bash

resizesize=50
  
case "$1" in
        "addleft")
            hyprctl dispatch resizeactive $resizesize 0
            hyprctl dispatch moveactive -$resizesize 0
            exit 0
            ;;
        "addright")
            hyprctl dispatch resizeactive $resizesize 0
            exit 0
            ;;
        "addup")
            hyprctl dispatch resizeactive 0 $resizesize
            hyprctl dispatch moveactive 0 -$resizesize
            exit 0
            ;;
        "adddown")
            hyprctl dispatch resizeactive 0 $resizesize
            exit 0
            ;;
        "delleft")
            hyprctl dispatch resizeactive -$resizesize 0
            hyprctl dispatch moveactive $resizesize 0
            exit 0
            ;;
        "delright")
            hyprctl dispatch resizeactive -$resizesize 0
            exit 0
            ;;
        "delup")
            hyprctl dispatch resizeactive 0 -$resizesize
            hyprctl dispatch moveactive 0 $resizesize
            exit 0
            ;;
        "deldown")
            hyprctl dispatch resizeactive 0 -$resizesize
            exit 0
            ;;
    esac
